# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/views/ListWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListWindow(object):
    def setupUi(self, ListWindow):
        ListWindow.setObjectName("ListWindow")
        ListWindow.resize(500, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ListWindow.sizePolicy().hasHeightForWidth())
        ListWindow.setSizePolicy(sizePolicy)
        ListWindow.setMinimumSize(QtCore.QSize(500, 300))
        ListWindow.setMaximumSize(QtCore.QSize(500, 300))
        ListWindow.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/db.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ListWindow.setWindowIcon(icon)
        ListWindow.setToolTipDuration(-1)
        ListWindow.setStyleSheet("* {\n"
"   color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QStatusBar{\n"
"  background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"QToolTip {\n"
"  color: black;\n"
"}\n"
"\n"
"QLabel {\n"
"  color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar:vertical {              \n"
"    border: unset;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(40, 40, 40, 255), stop:0.532663 rgba(29, 29, 29, 255));\n"
"    width:10px;    \n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    border-radius: 4px;\n"
"    background-color: rgb(190, 0, 105);\n"
"    min-height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    height: 0px;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}")
        ListWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.central_widget = QtWidgets.QWidget(ListWindow)
        self.central_widget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_frame = QtWidgets.QFrame(self.central_widget)
        self.main_frame.setStyleSheet("#main_frame {\n"
"    border: 1px solid rgb(124, 124, 124);\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(40, 40, 40, 255), stop:0.532663 rgba(29, 29, 29, 255));\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_frame.sizePolicy().hasHeightForWidth())
        self.title_frame.setSizePolicy(sizePolicy)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 30))
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setGeometry(QtCore.QRect(3, 1, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("")
        self.title_label.setObjectName("title_label")
        self.title_btns_frame = QtWidgets.QFrame(self.title_frame)
        self.title_btns_frame.setGeometry(QtCore.QRect(379, -7, 111, 31))
        self.title_btns_frame.setStyleSheet("QPushButton\n"
"{\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"}")
        self.title_btns_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_btns_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_btns_frame.setObjectName("title_btns_frame")
        self.minimize_btn = QtWidgets.QPushButton(self.title_btns_frame)
        self.minimize_btn.setGeometry(QtCore.QRect(54, 10, 16, 16))
        self.minimize_btn.setMinimumSize(QtCore.QSize(16, 16))
        self.minimize_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.minimize_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(255, 200, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 200, 0, 220);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"  background-color: rgba(255, 200, 0, 200);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"  background-color: rgb(150, 150, 150);\n"
"}")
        self.minimize_btn.setText("")
        self.minimize_btn.setObjectName("minimize_btn")
        self.exit_btn = QtWidgets.QPushButton(self.title_btns_frame)
        self.exit_btn.setGeometry(QtCore.QRect(80, 10, 16, 16))
        self.exit_btn.setMinimumSize(QtCore.QSize(16, 16))
        self.exit_btn.setMaximumSize(QtCore.QSize(16, 16))
        self.exit_btn.setStyleSheet("QPushButton\n"
"{\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 0, 0, 220);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"  background-color: rgba(255, 0, 0, 200);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"  background-color: rgb(150, 150, 150);\n"
"}")
        self.exit_btn.setText("")
        self.exit_btn.setObjectName("exit_btn")
        self.verticalLayout.addWidget(self.title_frame)
        self.content_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content_frame.sizePolicy().hasHeightForWidth())
        self.content_frame.setSizePolicy(sizePolicy)
        self.content_frame.setMinimumSize(QtCore.QSize(0, 230))
        self.content_frame.setStyleSheet("")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.content_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.file_list_view = QtWidgets.QListView(self.content_frame)
        self.file_list_view.setMaximumSize(QtCore.QSize(16777215, 230))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.file_list_view.setFont(font)
        self.file_list_view.setStyleSheet("QListView {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid  rgba(255, 255, 255, 100);\n"
"    background-color: rgb(40, 40, 40);\n"
"    text-align: center;\n"
"    outline: none;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QListView::item:selected:!active {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background-color: rgb(127, 0, 74);\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"    background-color:  rgb(190, 0, 105);\n"
"}")
        self.file_list_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.file_list_view.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.file_list_view.setObjectName("file_list_view")
        self.horizontalLayout_3.addWidget(self.file_list_view)
        self.actions_frame = QtWidgets.QFrame(self.content_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actions_frame.sizePolicy().hasHeightForWidth())
        self.actions_frame.setSizePolicy(sizePolicy)
        self.actions_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.actions_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.actions_frame.setStyleSheet("QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(200, 0, 120);\n"
"}\n"
"\n"
"QPushButton:hover:pressed\n"
"{\n"
"  background-color: rgb(180, 0, 100);\n"
"}\n"
"\n"
"QPushButton{\n"
"  background-color: rgb(190, 0, 105);\n"
"  color: rgb(255, 255, 255);\n"
"  border: unset;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"  color: rgb(95, 95, 95);\n"
"  background-color: rgb(150, 150, 150);\n"
"}")
        self.actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.actions_frame.setObjectName("actions_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.actions_frame)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(15, -1, 5, 100)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.done_btn = QtWidgets.QPushButton(self.actions_frame)
        self.done_btn.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.done_btn.setFont(font)
        self.done_btn.setObjectName("done_btn")
        self.verticalLayout_3.addWidget(self.done_btn)
        spacerItem = QtWidgets.QSpacerItem(0, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.add_btn = QtWidgets.QPushButton(self.actions_frame)
        self.add_btn.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.add_btn.setFont(font)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout_3.addWidget(self.add_btn)
        spacerItem1 = QtWidgets.QSpacerItem(0, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.remove_btn = QtWidgets.QPushButton(self.actions_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_btn.sizePolicy().hasHeightForWidth())
        self.remove_btn.setSizePolicy(sizePolicy)
        self.remove_btn.setMinimumSize(QtCore.QSize(100, 30))
        self.remove_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.remove_btn.setFont(font)
        self.remove_btn.setObjectName("remove_btn")
        self.verticalLayout_3.addWidget(self.remove_btn)
        spacerItem2 = QtWidgets.QSpacerItem(0, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_3.addWidget(self.actions_frame)
        self.verticalLayout.addWidget(self.content_frame)
        self.verticalLayout_2.addWidget(self.main_frame)
        ListWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(ListWindow)
        QtCore.QMetaObject.connectSlotsByName(ListWindow)

    def retranslateUi(self, ListWindow):
        _translate = QtCore.QCoreApplication.translate
        self.title_label.setText(_translate("ListWindow", "List Window"))
        self.minimize_btn.setToolTip(_translate("ListWindow", "Minimize"))
        self.exit_btn.setToolTip(_translate("ListWindow", "Exit"))
        self.done_btn.setText(_translate("ListWindow", "Done"))
        self.add_btn.setText(_translate("ListWindow", "Add"))
        self.remove_btn.setText(_translate("ListWindow", "Remove"))
from ui.resources.resources import *
