# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/views/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/db.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("* {\n"
"   font: 9pt \"Montserrat\";\n"
"   color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QFrame{\n"
"  background-color: rgb(31, 38, 79);\n"
"}\n"
"\n"
"QStatusBar{\n"
"  background-color: rgb(31, 38, 79);\n"
"}\n"
"\n"
"#actionsGrpBox > QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(11, 103, 198);\n"
"}\n"
"\n"
"#actionsGrpBox > QPushButton:hover:pressed\n"
"{\n"
"  background-color: rgb(10, 89, 170);\n"
"}\n"
"\n"
"#actionsGrpBox > QPushButton{\n"
"  background-color: rgb(31, 94, 255);\n"
"  color: rgb(255, 255, 255);\n"
"  border: unset;\n"
"  border-radius: 4px;\n"
"  font-size:12px;\n"
"}\n"
"\n"
"#actionsGrpBox > QPushButton:disabled{\n"
"  background-color: rgb(185, 186, 189);\n"
"}\n"
"\n"
"QToolTip {\n"
"  color: black;\n"
"}\n"
"\n"
"QLabel {\n"
"  color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QGroupBox {\n"
"  color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox {\n"
"  color: rgb(255, 255, 255);\n"
"  border: 1px solid  rgb(255, 255, 255);\n"
"  background-color: rgb(31, 38, 79);\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QListView {\n"
" border: unset;\n"
"}\n"
"\n"
"QListView::item:selected:!active {\n"
"  color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"  background-color: rgb(10, 89, 170);\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"  background-color: rgb(11, 103, 198);\n"
"}\n"
"\n"
"QListView{\n"
"  outline: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {              \n"
"    border: unset;\n"
"    background-color: rgb(31, 38, 79);\n"
"    width:10px;    \n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    border-radius: 4px;\n"
"    background-color: rgb(11, 95, 181);\n"
"    min-height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    height: 0px;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gameGrpBox = QtWidgets.QGroupBox(self.frame)
        self.gameGrpBox.setMinimumSize(QtCore.QSize(0, 0))
        self.gameGrpBox.setObjectName("gameGrpBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gameGrpBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gameCmbBox = QtWidgets.QComboBox(self.gameGrpBox)
        self.gameCmbBox.setMinimumSize(QtCore.QSize(200, 0))
        self.gameCmbBox.setObjectName("gameCmbBox")
        self.horizontalLayout_2.addWidget(self.gameCmbBox)
        self.horizontalLayout_3.addWidget(self.gameGrpBox)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.platformGrpBox = QtWidgets.QGroupBox(self.frame)
        self.platformGrpBox.setObjectName("platformGrpBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.platformGrpBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.platformCmbBox = QtWidgets.QComboBox(self.platformGrpBox)
        self.platformCmbBox.setMinimumSize(QtCore.QSize(100, 0))
        self.platformCmbBox.setObjectName("platformCmbBox")
        self.horizontalLayout_4.addWidget(self.platformCmbBox)
        self.horizontalLayout_3.addWidget(self.platformGrpBox)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.actionsGrpBox = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionsGrpBox.sizePolicy().hasHeightForWidth())
        self.actionsGrpBox.setSizePolicy(sizePolicy)
        self.actionsGrpBox.setMinimumSize(QtCore.QSize(259, 0))
        self.actionsGrpBox.setMaximumSize(QtCore.QSize(259, 16777215))
        self.actionsGrpBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.actionsGrpBox.setObjectName("actionsGrpBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.actionsGrpBox)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openBtn = QtWidgets.QPushButton(self.actionsGrpBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openBtn.sizePolicy().hasHeightForWidth())
        self.openBtn.setSizePolicy(sizePolicy)
        self.openBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.openBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.openBtn.setToolTip("")
        self.openBtn.setWhatsThis("")
        self.openBtn.setText("")
        self.openBtn.setObjectName("openBtn")
        self.horizontalLayout.addWidget(self.openBtn)
        self.saveBtn = QtWidgets.QPushButton(self.actionsGrpBox)
        self.saveBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.saveBtn.setText("")
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.saveAsBtn = QtWidgets.QPushButton(self.actionsGrpBox)
        self.saveAsBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.saveAsBtn.setText("")
        self.saveAsBtn.setObjectName("saveAsBtn")
        self.horizontalLayout.addWidget(self.saveAsBtn)
        self.disableBtn = QtWidgets.QPushButton(self.actionsGrpBox)
        self.disableBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.disableBtn.setText("")
        self.disableBtn.setObjectName("disableBtn")
        self.horizontalLayout.addWidget(self.disableBtn)
        self.importBtn = QtWidgets.QPushButton(self.actionsGrpBox)
        self.importBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.importBtn.setText("")
        self.importBtn.setObjectName("importBtn")
        self.horizontalLayout.addWidget(self.importBtn)
        self.exportBtn = QtWidgets.QPushButton(self.actionsGrpBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportBtn.sizePolicy().hasHeightForWidth())
        self.exportBtn.setSizePolicy(sizePolicy)
        self.exportBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.exportBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.exportBtn.setText("")
        self.exportBtn.setObjectName("exportBtn")
        self.horizontalLayout.addWidget(self.exportBtn)
        self.horizontalLayout_3.addWidget(self.actionsGrpBox)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame)
        self.contentGrpBox = QtWidgets.QGroupBox(self.frame_2)
        self.contentGrpBox.setMinimumSize(QtCore.QSize(0, 0))
        self.contentGrpBox.setObjectName("contentGrpBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.contentGrpBox)
        self.verticalLayout_3.setContentsMargins(0, 5, 0, 1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.contentListView = QtWidgets.QListView(self.contentGrpBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentListView.sizePolicy().hasHeightForWidth())
        self.contentListView.setSizePolicy(sizePolicy)
        self.contentListView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.contentListView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.contentListView.setObjectName("contentListView")
        self.verticalLayout_3.addWidget(self.contentListView)
        self.verticalLayout.addWidget(self.contentGrpBox)
        self.verticalLayout_2.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.gameGrpBox.setTitle(_translate("MainWindow", "Game"))
        self.platformGrpBox.setTitle(_translate("MainWindow", "Platform"))
        self.actionsGrpBox.setTitle(_translate("MainWindow", "Actions"))
        self.contentGrpBox.setTitle(_translate("MainWindow", "Content"))
from ui.resources.resources import *
