# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/views/MessageWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MessageWindow(object):
    def setupUi(self, MessageWindow):
        MessageWindow.setObjectName("MessageWindow")
        MessageWindow.resize(550, 220)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MessageWindow.sizePolicy().hasHeightForWidth())
        MessageWindow.setSizePolicy(sizePolicy)
        MessageWindow.setMinimumSize(QtCore.QSize(550, 220))
        MessageWindow.setMaximumSize(QtCore.QSize(550, 220))
        MessageWindow.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/db.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MessageWindow.setWindowIcon(icon)
        MessageWindow.setToolTipDuration(-1)
        MessageWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.central_widget = QtWidgets.QWidget(MessageWindow)
        self.central_widget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_frame = QtWidgets.QFrame(self.central_widget)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_frame.sizePolicy().hasHeightForWidth())
        self.title_frame.setSizePolicy(sizePolicy)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 15))
        self.title_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dummy = QtWidgets.QVBoxLayout()
        self.dummy.setObjectName("dummy")
        self.horizontalLayout.addLayout(self.dummy)
        self.verticalLayout.addWidget(self.title_frame)
        self.message_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_frame.sizePolicy().hasHeightForWidth())
        self.message_frame.setSizePolicy(sizePolicy)
        self.message_frame.setMinimumSize(QtCore.QSize(0, 60))
        self.message_frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.message_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.message_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.message_frame.setObjectName("message_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.message_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.message_icon = QtWidgets.QLabel(self.message_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_icon.sizePolicy().hasHeightForWidth())
        self.message_icon.setSizePolicy(sizePolicy)
        self.message_icon.setMinimumSize(QtCore.QSize(60, 60))
        self.message_icon.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.message_icon.setFont(font)
        self.message_icon.setText("")
        self.message_icon.setObjectName("message_icon")
        self.horizontalLayout_3.addWidget(self.message_icon)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.message_label = QtWidgets.QLabel(self.message_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.message_label.setFont(font)
        self.message_label.setStyleSheet("")
        self.message_label.setObjectName("message_label")
        self.horizontalLayout_3.addWidget(self.message_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.message_frame)
        self.actions_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actions_frame.sizePolicy().hasHeightForWidth())
        self.actions_frame.setSizePolicy(sizePolicy)
        self.actions_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.actions_frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.actions_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.actions_frame.setObjectName("actions_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.actions_frame)
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.yes_btn = QtWidgets.QPushButton(self.actions_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yes_btn.sizePolicy().hasHeightForWidth())
        self.yes_btn.setSizePolicy(sizePolicy)
        self.yes_btn.setMinimumSize(QtCore.QSize(100, 35))
        self.yes_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.yes_btn.setFont(font)
        self.yes_btn.setObjectName("yes_btn")
        self.horizontalLayout_5.addWidget(self.yes_btn)
        spacerItem4 = QtWidgets.QSpacerItem(30, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.no_btn = QtWidgets.QPushButton(self.actions_frame)
        self.no_btn.setMinimumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.no_btn.setFont(font)
        self.no_btn.setObjectName("no_btn")
        self.horizontalLayout_5.addWidget(self.no_btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.actions_frame)
        self.verticalLayout_2.addWidget(self.main_frame)
        MessageWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MessageWindow)
        QtCore.QMetaObject.connectSlotsByName(MessageWindow)

    def retranslateUi(self, MessageWindow):
        _translate = QtCore.QCoreApplication.translate
        self.message_label.setText(_translate("MessageWindow", "Message text"))
        self.yes_btn.setText(_translate("MessageWindow", "Yes"))
        self.no_btn.setText(_translate("MessageWindow", "No"))
from ui.resources.resources import *
