# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/views/ProgressWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgressWindow(object):
    def setupUi(self, ProgressWindow):
        ProgressWindow.setObjectName("ProgressWindow")
        ProgressWindow.resize(400, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProgressWindow.sizePolicy().hasHeightForWidth())
        ProgressWindow.setSizePolicy(sizePolicy)
        ProgressWindow.setMinimumSize(QtCore.QSize(400, 100))
        ProgressWindow.setMaximumSize(QtCore.QSize(500, 200))
        ProgressWindow.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/db.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ProgressWindow.setWindowIcon(icon)
        ProgressWindow.setToolTipDuration(-1)
        ProgressWindow.setStyleSheet("* {\n"
"   color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QStatusBar{\n"
"  background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"QToolTip {\n"
"  color: black;\n"
"}\n"
"\n"
"QLabel {\n"
"  color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListView {\n"
" border: unset;\n"
"}\n"
"\n"
"QListView::item:selected:!active {\n"
"  color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"  background-color: rgb(10, 89, 170);\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"  background-color: rgb(11, 103, 198);\n"
"}\n"
"\n"
"QListView{\n"
"  outline: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {              \n"
"    border: unset;\n"
"    background-color: rgb(31, 38, 79);\n"
"    width:10px;    \n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    border-radius: 4px;\n"
"    background-color: rgb(11, 95, 181);\n"
"    min-height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    height: 0px;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}")
        ProgressWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.central_widget = QtWidgets.QWidget(ProgressWindow)
        self.central_widget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_frame = QtWidgets.QFrame(self.central_widget)
        self.main_frame.setStyleSheet("#main_frame {\n"
"    border: 1px solid rgb(124, 124, 124);\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(40, 40, 40, 255), stop:0.532663 rgba(29, 29, 29, 255));\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_frame.sizePolicy().hasHeightForWidth())
        self.title_frame.setSizePolicy(sizePolicy)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 25))
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setGeometry(QtCore.QRect(150, 2, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("")
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_frame)
        self.progress_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_frame.sizePolicy().hasHeightForWidth())
        self.progress_frame.setSizePolicy(sizePolicy)
        self.progress_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.progress_frame.setStyleSheet("")
        self.progress_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_frame.setObjectName("progress_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.progress_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 8)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progress_bar = QtWidgets.QProgressBar(self.progress_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar.sizePolicy().hasHeightForWidth())
        self.progress_bar.setSizePolicy(sizePolicy)
        self.progress_bar.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.progress_bar.setFont(font)
        self.progress_bar.setStyleSheet("QProgressBar\n"
"{\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid  rgba(255, 255, 255, 100);\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: rgb(210, 0, 120);\n"
"}")
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.progress_bar.setTextVisible(True)
        self.progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.progress_bar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayout_3.addWidget(self.progress_bar)
        self.verticalLayout.addWidget(self.progress_frame)
        self.verticalLayout_2.addWidget(self.main_frame)
        ProgressWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(ProgressWindow)
        QtCore.QMetaObject.connectSlotsByName(ProgressWindow)

    def retranslateUi(self, ProgressWindow):
        _translate = QtCore.QCoreApplication.translate
        self.title_label.setText(_translate("ProgressWindow", "Processing..."))
from ui.resources.resources import *
